### ISSUE TITLE
Field type choices for field creation

### ISSUE THREAD

**Issue by m0r0n** [emartech/api_docs#2]
Hi Emarsys team,

Referring to source/suite/contacts/contact_field_create.rst I would wish to have a list of options somewhere. What kind of field types (application_type) can I create with that call what are their specifications?

Cheers,
Christian

**Comment by zerga5** [comment]
Dear Christian,

Thank you for your kind request. The document was updated with the missing information, you can find it here: https://dev.emarsys.com/suite/contacts/contact_field_create.html.
Feel free to share your recommendations in the future as well.

Enikő
