### ISSUE TITLE
Unsubscribing a Contact from an Email Campaign

### ISSUE THREAD

**Issue by xc0n42** [emartech/api_docs#3]
Some notes: 

1) Note:
"which target your own website and unsubscribing the user only from the specific email campaign, not from all campaigns."
This is misleading as Emarsys do not really have real multiple optins. 
Better:
"which target your own website and unsubscribing the user by updating specific fields in his user profile (e.g. a newsletter flag) and count the unsubscription for the statistics of the specific campaign"

2) launch_id must be launchlist_id

3) Explanation of where to get the email_id and launch(list)_id from:
"In your campaign create a new link which points to the unsubscription page of your website. You can use $cid$ and $llid$. $cid$ will be replaced with the email_id and $llid$ will be replaced with the launch(list)_id. Please make sure that you track the link in Emarsys suite. 
Example: http://yourwebsite.com/unsubscribe.html?email_id=$cid$&launchlist_id=$llid$"

**Comment by zerga5** [comment]
Doc updated with the info. Thank you for your kind comments.
